# Generated by Django 6.0.7 on 2026-08-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_text', models.CharField(max_length=200)),
                ('password_strength', models.IntegerField(default=0)),
                ('password_attributes', models.JSONField(default=dict)),
            ],
        ),
    ]
