# Generated by Django 6.0.7 on 2026-10-09 08:44

import PasswordCheck.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordCheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password_attributes',
            field=models.JSONField(default=PasswordCheck.models.default_password_attributes),
        ),
        migrations.AlterField(
            model_name='password',
            name='password_strength',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='password',
            name='password_text',
            field=models.CharField(max_length=30),
        ),
    ]
